### PR TITLE
Build Birdfont on Travis CI, generate and publish AppImage, closes #55, closes #77

### LINKED ISSUE #55: Provide free version for Linux as AppImage (alternatively to Flatpak)
Please, make AppImage builds for "free" version, as alternative to Flatpak

- http://github.com/appimage

### LINKED ISSUE #77: Continuous builds on Travis CI
Can we get this to build on Travis CI on a Ubuntu 14.04 (trusty) instance?

### PR DESCRIPTION
**Pull request by probonopd**
* Closes #55
* Closes #77

This PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Here is an AppImage for testing: https://github.com/probonopd/birdfont/releases/tag/continuous

__PLEASE NOTE:__ For this to work, you need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
Removed the workarounds; for this I also had to make an adjustment in `SearchPaths.vala`; kindly review.

**Comment by probonopd** [comment]
Thanks for merging. Looks like you also need to enable this:
https://travis-ci.com/johanmattssonm/birdfont

And to set up `GITHUB_TOKEN` in Travis CI; please see https://github.com/probonopd/uploadtool.

If everything goes well, then an AppImage should appear on https://github.com/johanmattssonm/birdfont/releases for each git commit from thereon.

**Comment by johanmattssonm** [comment]
Thank you for the instructions, it was easy to follow them. I do have a few
questions. Do you plan to distribute the appimage on other sites as well?
Is there a way to only trigger builds when i push tags to the repo? I don't
maintain file format compatibility for builds that happen in
between releases.

**Comment by probonopd** [comment]
> Thank you for the instructions, it was easy to follow them. 

Thanks for the feedback, good to hear (even though I plan to make it even simpler in the future...)

> Do you plan to distribute the appimage on other sites as well?

No, I would just like to link to https://github.com/johanmattssonm/birdfont/releases from where users can choose to download either a release build or the continuous build (which may come in handy for testing purposes).

Is there a way to only trigger builds when i push tags to the repo?

> I think it happens automagically.

**Pull request merged**
