### PR TITLE
Add an automatic scaling tool

### PR DESCRIPTION
**Pull request by novalis**

### CODE REVIEW

**Comment by novalis** [comment]
I think we could also add an action to scale from (baseline to x-height).  I wasn't sure if this patch should also move the bottom of the shape to the baseline.  Happy to do it either way.

**Comment by johanmattssonm** [comment]
Thank you.

**Comment by johanmattssonm** [comment]
Moving path to baseline seems like the right thing to to do, in most cases.

The method names are a bit confusing in ResizeTool. Resize takes the position of the resize handle as an argument and resize_selected_paths scales the selected paths.

It might also be a good thing to do something else for glyphs with a descender. I think it would be best to create a small database with ascender and descender information and scale the glyphs it appropriately. If I have enough time will I create the database later this week.

**Comment by johanmattssonm** [comment]
... but I have no idea how to handle diacritics.

**Comment by novalis** [comment]
It would be cool to be able to mark a top point and a baseline point on a glyph. Basically just an attribute on the control points. This would allow automatic scaling to handle descenders and diacritics. 



-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
